### ISSUE TITLE
Packages and foodItem

### ISSUE THREAD

**Issue by AdamDari123** [fr0st-iwnl/tomato-delivery#1]
Hi, when i installed the code it has a problem with bcrypt, but when you resolve it (just uninstall and install bcrypt) it has a problem displaying food data cuz it says that `!cartItems[id]` is undefined at line 14 in FoodItem.jsx.
I tried to resolve the problem but i just started react 3 days ago and im not very very good 😅 (before to install your code i tried to do it by myself following the video on YouTube, but it gave me the same error, so i don't know if the guy wrote something off video or what)
Plz help 😪

EDIT: i figured out that the problem is in the API to get the cart data (http://localhost:4000/api/cart/get), in the backend console it says `JsonWebTokenError: invalid signature
    at /Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/jsonwebtoken/verify.js:171:19
    at getSecret (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/jsonwebtoken/verify.js:97:14)
    at module.exports [as verify] (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/jsonwebtoken/verify.js:101:10)
    at authMiddleware (file:///Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/middleware/auth.js:9:34)
    at Layer.handle [as handle_request] (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/Adam_Dari/ReactProjects/PizzeriaFuego/backend/node_modules/express/lib/router/index.js:346:12)` i dont know if this is the main reason of the problem. GOOD LUCK

**Comment by fr0st-iwnl** [comment]
Hi,

It looks like the JWT verification error might be due to an issue with the secret key. Please make sure you have correctly placed your JWT secret key in the `.env` file and let me know!

**Comment by AdamDari123** [comment]
Yeah it was, BRUH😭

**Comment by Khalid7255** [comment]
Hi bro I'm facing issues in that project can you please contact me to guide please 
7387387255
